### PR TITLE
[FIX] fix string parse in GetMessageHelper

### PR DESCRIPTION
**Pull request by marcosdenoni**
verify if bodyLength is not overflow the lenght of response

### CODE REVIEW

**Comment by jstedfast** [comment]
The problem with the patch is that it is a hack at best because the reason that this problem exists in the first place is that the integer value between the {}'s is a byte count, not a character count, and so the code needs to count byte offsets instead of char offsets.

Ideally, the fix would require changes to the parser to work with byte arrays rather than strings - not only would that fix *this* bug, but also bugs where a message has MIME parts and/or headers in different charset encodings.

Short of that, the best you'll be able to do is to "convert" the string back into bytes, count off the number of bytes, and then convert the sub-array back into a string.

(Note: I use "convert" in quotes because you might be able to use some tricks, depending on the origin charset, to count bytes without having to do the actual conversion and just keep a running total as you iterate over the characters in the string.)

**Comment by jstedfast** [comment]
Note: My note above *assumes* that "converting" from UTF-16 back to whatever the origin charset was is completely reversible. This may not be the case, however, since it is possible for the original raw message blob to contain illegal multi-byte sequences that the TextReader being used to read the IMAP response simply drops in order to force the bytes into UTF-16.

**Comment by jstedfast** [comment]
Did a quick check in the code to see what `System.Text.Encoding` the `ImapClient` used and it just uses `new StreamReader (stream);` which, according to the docs on MSDN, means that the `StreamReader` uses the UTF8 encoding.

That encoding is going to make this the least likely to work properly because the UTF8 encoding will drop anything that isn't valid UTF-8 and therefor you'll get into a situation where you will not be able to reliably reverse the encoding conversion.

For maximum probability of working, you'll need the `StreamReader` to use the ISO-8859-1 encoding instead.

Of course, by using ISO-8859-1, you would probably be able to treat byte and char counts as the same (unless the ISO-8859-1 encoding implementation drops the nul-byte when encountered in the input?).

However, this opens up other problems such as the fact that only ISO-8859-1 messages will render properly.



Anyways... this is why I suggested parsing byte arrays rather than strings :)

**Comment by jstedfast** [comment]
Here's the best possible fix that can be done with the current code:

1. Change https://github.com/bertjohnson/OpaqueMail/blob/master/OpaqueMail/Imap/ImapClient.cs#L689 to use `new StreamReader (stream, Encoding.GetEncoding ("iso-8859-1"));`

2. Change the following code:

```csharp
                int.TryParse(Functions.ReturnBetween(firstLine, "BODY[] {", "}"), out bodyLength);
                if (bodyLength > 0)
                    response = response.Substring(lineBreak + 2, bodyLength);
                else
                {
                    response = response.Substring(response.IndexOf("\r\n") + 2);
                    response = response.Substring(0, response.Length - 2);
                }

                MailMessage message = new MailMessage(response, ProcessingFlags);
```

to this:

```csharp
                int.TryParse(Functions.ReturnBetween(firstLine, "BODY[] {", "}"), out bodyLength);
                if (bodyLength > 0)
                    response = response.Substring(lineBreak + 2, bodyLength);
                else
                {
                    response = response.Substring(response.IndexOf("\r\n") + 2);
                    response = response.Substring(0, response.Length - 2);
                }

                // get the raw bytes 
                var latin1 = Encoding.GetEncoding ("iso-8859-1");
                var bytes = latin1.GetBytes (response);
                
                // convert to UTF-8, like the old code did...
                var utf8 = Encoding.GetEncoding ("UTF-8", new EncoderReplacementFallback (""),  new DecoderReplacementFallback (""));
                response = utf8.GetString (bytes);

                MailMessage message = new MailMessage(response, ProcessingFlags);
```

**Comment by marcosdenoni** [comment]
Converting the response to bytes not can resolve problem, the error occurs on 
` response = response.Substring(lineBreak + 2, bodyLength); `
because bodyLength is more bigger than lenght of response.

In this point convert the response to bytes and realize a split of bytes to get message correct?

**Comment by jstedfast** [comment]
You missed the fact that you need to change the StreamReader to use ISO-8859-1 instead of UTF-8.

ISO-8859-1 is an encoding where there is a 1:1 mapping of bytes to chars and back.

For UTF-8, each char can map to anywhere between 1 and 3 bytes.

This is why the length value is too long in some cases and why you are needing to cut it short.

**Comment by jstedfast** [comment]
The encoding that the StreamReader uses is the important part of this fix. In fact, the StreamReader encoding fix is the only fix *necessary* for this to work. The Conversion to bytes and back using UTF-8 is only needed in order to maintain "compatibility" with the existing code that assumes all messages get converted to strings using UTF-8 and not ISO-8859-1.

**Comment by marcosdenoni** [comment]
Thanks for this detail, really, had not checked the encode.

I tested and work fine

**Comment by bertjohnson** [comment]
marcosdenoni and jstedfast, thanks for digging into this.

Jeffrey is right that the handling of character counts vs. byte counts is error-prone. The fix above looks good for this situation, although I'm concerned about performance. Ideally, we'd implement a better tokenizer and process consistently on bytes. Realistically, I don't know if or when I'll get to that.

As you can see, jstedfast is extremely responsive and knowledgeable about email. His [MailKit project](https://github.com/jstedfast/MailKit) is newer than OpaqueMail and has surpassed this in many ways, so I recommend checking it out.

**Comment by bertjohnson** [comment]
marcosdenoni and jstedfast, thanks again for exploring this.

I've incorporated Jeffrey's fix from 10/24 into OpaqueMail 2.3.0.

**Pull request closed without merging**
